"""Baseline migration

Revision ID: 465e555b65dd
Revises: 8894adf9fa1a
Create Date: 2024-12-28 19:07:53.056576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '465e555b65dd'
down_revision = '8894adf9fa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
